Description: >
  This template used to create an Application Load Balancer that exposes ECS services of rb2019.

Parameters:
  EnvironmentName:
    Description: An environment name to resource name prefix
    Type: String
  VPC:
    Description: Choose which VPC
    Type: AWS::EC2::VPC::Id
  Subnets:
    Description: Choose which subnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Description: Select Security Group for ALB
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "rb2019-${EnvironmentName}"
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: project
          Value: rb2019

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-URL"
